#!/usr/bin/env bash
# configures a new Ubuntu machine

# Install nginx on web-01 server
set -e

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="\n\tadd_header X-Served-By $HOST_NAME;\n"
if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i "/server_name _;/a\\$HEADER" /etc/nginx/sites-available/default
fi

# Create a first index.html page
echo "Hello World!" > /var/www/html/index.html

# Add to the nginx configuration file a redirection to another page
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    sed -i "/server_name _;/a\\$REDIRECT" /etc/nginx/sites-available/default
fi

# Add to the nginx configuration file an error page 404
ERROR_PAGE="\n\terror_page 404 /custom_404.html;\n"
if ! grep -q "error_page 404" /etc/nginx/sites-available/default; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "/server_name _;/a\\$ERROR_PAGE" /etc/nginx/sites-available/default
fi

# Restart nginx service
service nginx restart
